defmodule WandererApp.Repo.Migrations.AddGroupMapAccessGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_map_synced_members_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_map_access_grant_id, :uuid, null: false
      add :access_list_member_id, :uuid, null: false
    end

    create table(:group_map_access_grants_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:group_map_synced_members_v1) do
      modify :group_map_access_grant_id,
             references(:group_map_access_grants_v1,
               column: :id,
               name: "group_map_synced_members_v1_group_map_access_grant_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )

      modify :access_list_member_id,
             references(:access_list_members_v1,
               column: :id,
               name: "group_map_synced_members_v1_access_list_member_id_fkey",
               type: :uuid,
               on_delete: :delete_all
             )
    end

    create unique_index(:group_map_synced_members_v1, [:access_list_member_id],
             name: "group_map_synced_members_v1_uniq_access_list_member_index"
           )

    alter table(:group_map_access_grants_v1) do
      add :role, :text, default: "viewer"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups_v1,
            column: :id,
            name: "group_map_access_grants_v1_group_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :access_list_id,
          references(:access_lists_v1,
            column: :id,
            name: "group_map_access_grants_v1_access_list_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:group_map_access_grants_v1, [:group_id, :access_list_id],
             name: "group_map_access_grants_v1_uniq_group_access_list_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_map_access_grants_v1, [:group_id, :access_list_id],
                     name: "group_map_access_grants_v1_uniq_group_access_list_index"
                   )

    drop constraint(:group_map_access_grants_v1, "group_map_access_grants_v1_group_id_fkey")

    drop constraint(:group_map_access_grants_v1, "group_map_access_grants_v1_access_list_id_fkey")

    alter table(:group_map_access_grants_v1) do
      remove :access_list_id
      remove :group_id
      remove :updated_at
      remove :inserted_at
      remove :role
    end

    drop_if_exists unique_index(:group_map_synced_members_v1, [:access_list_member_id],
                     name: "group_map_synced_members_v1_uniq_access_list_member_index"
                   )

    drop constraint(
           :group_map_synced_members_v1,
           "group_map_synced_members_v1_group_map_access_grant_id_fkey"
         )

    drop constraint(
           :group_map_synced_members_v1,
           "group_map_synced_members_v1_access_list_member_id_fkey"
         )

    alter table(:group_map_synced_members_v1) do
      modify :access_list_member_id, :uuid
      modify :group_map_access_grant_id, :uuid
    end

    drop table(:group_map_access_grants_v1)

    drop table(:group_map_synced_members_v1)
  end
end
