defmodule WandererApp.Repo.Migrations.ScoutStructureUnanchoringSince do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scout_structures_v1) do
      add :unanchoring_since, :utc_datetime
    end

    # CHEWY PATCH: backfill, so the Unanchoring board has a deadline for
    # runs already in progress instead of waiting out a fresh 7 days.
    #
    # The event log already records the exact transition: the LATEST
    # event whose status became Unanchoring from something else is the
    # start of the CURRENT run. "Latest", not "earliest": a cancelled
    # decommission restarts the full 7 days, so an older run's start
    # would under-predict — the one error direction that makes the
    # column dangerous.
    execute("""
    UPDATE scout_structures_v1 s
    SET unanchoring_since = e.started_at
    FROM (
      SELECT structure_id, MAX(observed_at) AS started_at
      FROM scout_structure_events_v1
      WHERE status_after = 'Unanchoring'
        AND status_before IS DISTINCT FROM 'Unanchoring'
      GROUP BY structure_id
    ) e
    WHERE s.structure_id = e.structure_id
      AND s.status = 'Unanchoring'
    """)

    # Rows unanchoring since before the event log existed: the last
    # change we recorded about them is the latest moment the run can
    # have started, which keeps the prediction an upper bound.
    execute("""
    UPDATE scout_structures_v1
    SET unanchoring_since = COALESCE(last_changed_at, first_seen_at)
    WHERE status = 'Unanchoring' AND unanchoring_since IS NULL
    """)
  end

  def down do
    alter table(:scout_structures_v1) do
      remove :unanchoring_since
    end
  end
end
