defmodule WandererApp.Repo.Migrations.AddScoutCoverageSpawnsLegsTotal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scout_system_coverage_v1) do
      add :spawns_found, :bigint
      add :legs_total, :bigint
    end
  end

  def down do
    alter table(:scout_system_coverage_v1) do
      remove :legs_total
      remove :spawns_found
    end
  end
end
