defmodule WandererApp.Repo.Migrations.ScoutStructureIdIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:scout_structure_sightings_v1, [:structure_id, :observed_at])
  end

  def down do
    drop_if_exists index(:scout_structure_sightings_v1, [:structure_id, :observed_at])
  end
end
