defmodule WandererApp.Repo.Migrations.AddScoutSystemCoverage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scout_system_coverage_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :solar_system_id, :bigint, null: false
      add :kind, :text, null: false
      add :observed_at, :utc_datetime, null: false
      add :character_eve_id, :text
      add :source, :text
      add :legs_scanned, :bigint
      add :sig_count, :bigint
      add :scanner_complete, :boolean
      add :map_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_system_coverage_v1, [:kind, :observed_at])

    create index(:scout_system_coverage_v1, [:observed_at])

    create unique_index(:scout_system_coverage_v1, [:solar_system_id, :kind],
             name: "scout_system_coverage_v1_uniq_coverage_index"
           )
  end

  def down do
    drop_if_exists unique_index(:scout_system_coverage_v1, [:solar_system_id, :kind],
                     name: "scout_system_coverage_v1_uniq_coverage_index"
                   )

    drop_if_exists index(:scout_system_coverage_v1, [:observed_at])

    drop_if_exists index(:scout_system_coverage_v1, [:kind, :observed_at])

    drop table(:scout_system_coverage_v1)
  end
end
