defmodule WandererApp.Repo.Migrations.ScoutStructureArchive do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scout_structures_v1) do
      add :archived_at, :utc_datetime
      add :archived_by_user_id, :uuid
    end
  end

  def down do
    alter table(:scout_structures_v1) do
      remove :archived_by_user_id
      remove :archived_at
    end
  end
end
