defmodule WandererApp.Repo.Migrations.AddScoutIntelSightings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scout_structure_sightings_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :observed_at, :utc_datetime, null: false
      add :character_name, :text, null: false
      add :event, :text, null: false, default: "seen"
      add :solar_system_id, :bigint, null: false
      add :solar_system_name, :text
      add :system_truesec, :float
      add :structure_id, :bigint, null: false
      add :type_id, :bigint
      add :structure_name, :text
      add :group_name, :text
      add :owner_id, :bigint
      add :owner_name, :text
      add :alliance_id, :bigint
      add :upkeep_state, :bigint
      add :upkeep_label, :text
      add :structure_state, :bigint
      add :state_label, :text
      add :vulnerable, :boolean
      add :anchoring, :boolean
      add :unanchoring, :boolean
      add :timer_seconds, :bigint
      add :timer_expires_at, :utc_datetime
      add :shield_pct, :bigint
      add :armor_pct, :bigint
      add :hull_pct, :bigint
      add :distance_m, :bigint
      add :map_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_structure_sightings_v1, [:timer_expires_at])

    create index(:scout_structure_sightings_v1, [:observed_at])

    create unique_index(:scout_structure_sightings_v1, [:structure_id, :observed_at, :event],
             name: "scout_structure_sightings_v1_uniq_sighting_index"
           )

    create table(:scout_spawn_sightings_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :observed_at, :utc_datetime, null: false
      add :character_name, :text, null: false
      add :solar_system_id, :bigint, null: false
      add :solar_system_name, :text
      add :system_truesec, :float
      add :location_type, :text
      add :location_name, :text, null: false, default: ""
      add :spawn_name, :text, null: false, default: ""
      add :spawn_category, :text
      add :anomaly_type, :text
      add :players_in_local, :bigint
      add :action_taken, :text
      add :outcome, :text
      add :entity_id, :bigint
      add :minutes_since_downtime, :bigint
      add :isk_value, :decimal
      add :map_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_spawn_sightings_v1, [:observed_at])

    create unique_index(
             :scout_spawn_sightings_v1,
             [:character_name, :observed_at, :solar_system_id, :location_name, :spawn_name],
             name: "scout_spawn_sightings_v1_uniq_sighting_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :scout_spawn_sightings_v1,
                     [
                       :character_name,
                       :observed_at,
                       :solar_system_id,
                       :location_name,
                       :spawn_name
                     ],
                     name: "scout_spawn_sightings_v1_uniq_sighting_index"
                   )

    drop_if_exists index(:scout_spawn_sightings_v1, [:observed_at])

    drop table(:scout_spawn_sightings_v1)

    drop_if_exists unique_index(
                     :scout_structure_sightings_v1,
                     [:structure_id, :observed_at, :event],
                     name: "scout_structure_sightings_v1_uniq_sighting_index"
                   )

    drop_if_exists index(:scout_structure_sightings_v1, [:observed_at])

    drop_if_exists index(:scout_structure_sightings_v1, [:timer_expires_at])

    drop table(:scout_structure_sightings_v1)
  end
end
