defmodule WandererApp.Repo.Migrations.AddScoutAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scout_assignments_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :assignment_id, :uuid, null: false
      add :solar_system_id, :bigint, null: false
      add :character_eve_id, :text, null: false
      add :kind, :text, null: false
      add :scope_label, :text
      add :expires_at, :utc_datetime, null: false
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_assignments_v1, [:expires_at])

    create index(:scout_assignments_v1, [:assignment_id])

    create index(:scout_assignments_v1, [:character_eve_id, :kind])

    create index(:scout_assignments_v1, [:solar_system_id, :kind])
  end

  def down do
    drop_if_exists index(:scout_assignments_v1, [:solar_system_id, :kind])

    drop_if_exists index(:scout_assignments_v1, [:character_eve_id, :kind])

    drop_if_exists index(:scout_assignments_v1, [:assignment_id])

    drop_if_exists index(:scout_assignments_v1, [:expires_at])

    drop table(:scout_assignments_v1)
  end
end
