defmodule WandererApp.Repo.Migrations.AddCorpRosterSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:corp_roster_snapshots_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :character_id, :text, null: false
      add :name, :text
      add :corporation_id, :bigint, null: false
      add :start_date, :utc_datetime
      add :logon_at, :utc_datetime
      add :logoff_at, :utc_datetime
      add :location_id, :bigint
      add :location_name, :text
      add :ship_type_id, :bigint
      add :ship_type_name, :text
      add :base_id, :bigint
      add :status, :text, null: false, default: "active"
      add :departed_at, :utc_datetime
      add :last_seen_in_roster_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:corp_roster_snapshots_v1, [:character_id],
             name: "corp_roster_snapshots_v1_uniq_character_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:corp_roster_snapshots_v1, [:character_id],
                     name: "corp_roster_snapshots_v1_uniq_character_id_index"
                   )

    drop table(:corp_roster_snapshots_v1)
  end
end
