defmodule WandererApp.Repo.Migrations.AddScoutStructurePresence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scout_structure_events_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :structure_id, :bigint, null: false
      add :solar_system_id, :bigint
      add :kind, :text, null: false
      add :observed_at, :utc_datetime, null: false
      add :status_before, :text
      add :status_after, :text
      add :changed_fields, {:array, :text}, null: false, default: []
      add :map_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_structure_events_v1, [:observed_at])

    create index(:scout_structure_events_v1, [:structure_id, :observed_at])

    create table(:scout_structures_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :structure_id, :bigint, null: false
      add :solar_system_id, :bigint, null: false
      add :type_id, :bigint
      add :structure_name, :text
      add :group_name, :text
      add :owner_id, :bigint
      add :owner_name, :text
      add :alliance_id, :bigint
      add :upkeep_state, :bigint
      add :structure_state, :bigint
      add :status, :text
      add :vulnerable, :boolean
      add :anchoring, :boolean
      add :unanchoring, :boolean
      add :timer_seconds, :bigint
      add :timer_expires_at, :utc_datetime
      add :shield_pct, :bigint
      add :armor_pct, :bigint
      add :hull_pct, :bigint
      add :pos_x, :float
      add :pos_y, :float
      add :pos_z, :float
      add :nearest_celestial, :text
      add :nearest_celestial_m, :bigint
      add :presence, :text, null: false, default: "seen"
      add :first_seen_at, :utc_datetime, null: false
      add :last_confirmed_at, :utc_datetime, null: false
      add :last_changed_at, :utc_datetime
      add :missing_count, :bigint, null: false, default: 0
      add :missing_since, :utc_datetime
      add :map_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:scout_structures_v1, [:last_confirmed_at])

    create index(:scout_structures_v1, [:timer_expires_at])

    create index(:scout_structures_v1, [:status])

    create index(:scout_structures_v1, [:presence])

    create index(:scout_structures_v1, [:solar_system_id])

    create unique_index(:scout_structures_v1, [:structure_id],
             name: "scout_structures_v1_uniq_structure_index"
           )

    # BACKFILL: seed current state from the newest sighting of each
    # structure the per-row feed ever recorded, so `/scout` does not go
    # blank the moment its boards switch data source. One row per
    # structure_id, newest first -- the same fold the LiveView used to do
    # at read time, done once here instead.
    #
    # Positions stay NULL: no historical sighting carries pos_x/y/z (the
    # client only started sending them with the snapshot feed), and a
    # structure with no stored position is never inside any blob's
    # horizon, so it can never be archived until it is observed again.
    # That is the intended fail-open -- a backfilled row can only ever be
    # confirmed or updated, never silently marked gone.
    #
    # `presence` seeds as 'seen' because that is what the row asserts; the
    # first real blob covering that system corrects anything long dead.
    # ON CONFLICT DO NOTHING keeps this safe to re-run.
    execute("""
    INSERT INTO scout_structures_v1 (
      id, structure_id, solar_system_id, type_id, structure_name, group_name,
      owner_id, owner_name, alliance_id, upkeep_state, structure_state, status,
      vulnerable, anchoring, unanchoring, timer_seconds, timer_expires_at,
      shield_pct, armor_pct, hull_pct, nearest_celestial, nearest_celestial_m,
      presence, first_seen_at, last_confirmed_at, missing_count, map_id,
      inserted_at, updated_at
    )
    SELECT DISTINCT ON (s.structure_id)
      gen_random_uuid(), s.structure_id, s.solar_system_id, s.type_id,
      s.structure_name, s.group_name, s.owner_id, s.owner_name, s.alliance_id,
      s.upkeep_state, s.structure_state, s.status, s.vulnerable, s.anchoring,
      s.unanchoring, s.timer_seconds, s.timer_expires_at, s.shield_pct,
      s.armor_pct, s.hull_pct, s.nearest_celestial, s.nearest_celestial_m,
      'seen', s.observed_at, s.observed_at, 0, s.map_id,
      (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
    FROM scout_structure_sightings_v1 s
    ORDER BY s.structure_id, s.observed_at DESC
    ON CONFLICT (structure_id) DO NOTHING
    """)
  end

  def down do
    drop_if_exists unique_index(:scout_structures_v1, [:structure_id],
                     name: "scout_structures_v1_uniq_structure_index"
                   )

    drop_if_exists index(:scout_structures_v1, [:solar_system_id])

    drop_if_exists index(:scout_structures_v1, [:presence])

    drop_if_exists index(:scout_structures_v1, [:status])

    drop_if_exists index(:scout_structures_v1, [:timer_expires_at])

    drop_if_exists index(:scout_structures_v1, [:last_confirmed_at])

    drop table(:scout_structures_v1)

    drop_if_exists index(:scout_structure_events_v1, [:structure_id, :observed_at])

    drop_if_exists index(:scout_structure_events_v1, [:observed_at])

    drop table(:scout_structure_events_v1)
  end
end
