defmodule WandererApp.Repo.Migrations.AddIdentitySuitePhase0 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:standing_grants_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :eve_character_id, :bigint
      add :eve_corporation_id, :bigint
      add :eve_alliance_id, :bigint
      add :state, :text, null: false, default: "blue"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:groups_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :kind, :text, null: false, default: "manual"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:user_identities_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "guest"
      add :state_computed_at, :utc_datetime
      add :disabled_at, :utc_datetime
      add :disabled_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:user_v1, column: :id, name: "user_identities_v1_user_id_fkey", type: :uuid),
          null: false

      add :main_character_id,
          references(:character_v1,
            column: :id,
            name: "user_identities_v1_main_character_id_fkey",
            type: :uuid
          )

      add :disabled_by_user_id,
          references(:user_v1,
            column: :id,
            name: "user_identities_v1_disabled_by_user_id_fkey",
            type: :uuid
          )
    end

    create unique_index(:user_identities_v1, [:user_id],
             name: "user_identities_v1_uniq_user_index"
           )

    create table(:owned_corporations_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :eve_corporation_id, :bigint, null: false
      add :name, :text, null: false
      add :ticker, :text
      add :alliance_id, :bigint
      add :alliance_name, :text
      add :enabled, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :director_character_id,
          references(:character_v1,
            column: :id,
            name: "owned_corporations_v1_director_character_id_fkey",
            type: :uuid
          )
    end

    create unique_index(:owned_corporations_v1, [:eve_corporation_id],
             name: "owned_corporations_v1_uniq_corporation_id_index"
           )

    create table(:group_memberships_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups_v1,
            column: :id,
            name: "group_memberships_v1_group_id_fkey",
            type: :uuid
          ),
          null: false

      add :user_id,
          references(:user_v1,
            column: :id,
            name: "group_memberships_v1_user_id_fkey",
            type: :uuid
          ),
          null: false

      add :granted_by_user_id,
          references(:user_v1,
            column: :id,
            name: "group_memberships_v1_granted_by_user_id_fkey",
            type: :uuid
          )
    end

    create unique_index(:group_memberships_v1, [:group_id, :user_id],
             name: "group_memberships_v1_uniq_group_user_index"
           )

    create table(:group_permissions_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :permission, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups_v1,
            column: :id,
            name: "group_permissions_v1_group_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create unique_index(:group_permissions_v1, [:group_id, :permission],
             name: "group_permissions_v1_uniq_group_permission_index"
           )

    create table(:group_auto_rules_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :match_kind, :text, null: false
      add :match_value, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups_v1,
            column: :id,
            name: "group_auto_rules_v1_group_id_fkey",
            type: :uuid
          ),
          null: false
    end

    create table(:audit_logs_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :details, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_user_id,
          references(:user_v1, column: :id, name: "audit_logs_v1_actor_user_id_fkey", type: :uuid)

      add :target_user_id,
          references(:user_v1,
            column: :id,
            name: "audit_logs_v1_target_user_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    drop constraint(:audit_logs_v1, "audit_logs_v1_actor_user_id_fkey")

    drop constraint(:audit_logs_v1, "audit_logs_v1_target_user_id_fkey")

    drop table(:audit_logs_v1)

    drop constraint(:group_auto_rules_v1, "group_auto_rules_v1_group_id_fkey")

    drop table(:group_auto_rules_v1)

    drop_if_exists unique_index(:group_permissions_v1, [:group_id, :permission],
                     name: "group_permissions_v1_uniq_group_permission_index"
                   )

    drop constraint(:group_permissions_v1, "group_permissions_v1_group_id_fkey")

    drop table(:group_permissions_v1)

    drop_if_exists unique_index(:group_memberships_v1, [:group_id, :user_id],
                     name: "group_memberships_v1_uniq_group_user_index"
                   )

    drop constraint(:group_memberships_v1, "group_memberships_v1_group_id_fkey")

    drop constraint(:group_memberships_v1, "group_memberships_v1_user_id_fkey")

    drop constraint(:group_memberships_v1, "group_memberships_v1_granted_by_user_id_fkey")

    drop table(:group_memberships_v1)

    drop_if_exists unique_index(:owned_corporations_v1, [:eve_corporation_id],
                     name: "owned_corporations_v1_uniq_corporation_id_index"
                   )

    drop constraint(:owned_corporations_v1, "owned_corporations_v1_director_character_id_fkey")

    drop table(:owned_corporations_v1)

    drop_if_exists unique_index(:user_identities_v1, [:user_id],
                     name: "user_identities_v1_uniq_user_index"
                   )

    drop constraint(:user_identities_v1, "user_identities_v1_user_id_fkey")

    drop constraint(:user_identities_v1, "user_identities_v1_main_character_id_fkey")

    drop constraint(:user_identities_v1, "user_identities_v1_disabled_by_user_id_fkey")

    drop table(:user_identities_v1)

    drop table(:groups_v1)

    drop table(:standing_grants_v1)
  end
end
