defmodule WandererApp.Repo.Migrations.AddSyncRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sync_runs_v1, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :feed_name, :text, null: false
      add :scope_key, :text, null: false
      add :status, :text, null: false, default: "ok"
      add :etag, :text
      add :last_checked_at, :utc_datetime
      add :last_success_at, :utc_datetime
      add :last_error, :text
      add :last_error_at, :utc_datetime
      add :consecutive_failures, :bigint, null: false, default: 0
      add :next_run_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sync_runs_v1, [:feed_name, :scope_key],
             name: "sync_runs_v1_uniq_feed_scope_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sync_runs_v1, [:feed_name, :scope_key],
                     name: "sync_runs_v1_uniq_feed_scope_index"
                   )

    drop table(:sync_runs_v1)
  end
end
